# Generated by Django 2.0 on 2017-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='連絡先')),
                ('school_name', models.CharField(max_length=255, verbose_name='学校名')),
                ('department', models.CharField(max_length=255, verbose_name='学部')),
                ('school_year', models.IntegerField(null=True, verbose_name='学年')),
                ('age', models.IntegerField(null=True, verbose_name='年齢')),
                ('graduation_year', models.IntegerField(null=True, verbose_name='卒業年度')),
                ('candidates_accuracy', models.IntegerField(null=True, verbose_name='確度（採用候補側）')),
                ('accuracy_reason', models.CharField(max_length=255, verbose_name='確度理由')),
                ('desired_degree', models.IntegerField(null=True, verbose_name='欲しい度合い')),
                ('competition', models.CharField(max_length=255, verbose_name='迷っている会社（競合）')),
                ('selection_phase', models.CharField(max_length=255, verbose_name='フェーズ')),
                ('selection_status', models.CharField(max_length=255, verbose_name='選考状況')),
                ('graduation_flg', models.IntegerField(null=True, verbose_name='卒業フラグ')),
                ('resume_flg', models.IntegerField(null=True, verbose_name='履歴書受領フラグ')),
                ('hiring_fee', models.IntegerField(null=True, verbose_name='採用フィー')),
                ('delete_flg', models.IntegerField(default=0, null=True, verbose_name='削除フラグ')),
                ('agreement_flg', models.IntegerField(null=True, verbose_name='内定承諾フラグ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
