# Generated by Django 2.0 on 2017-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='面接日')),
                ('time', models.TimeField(verbose_name='時間')),
                ('interviewer', models.CharField(max_length=255, verbose_name='面接官')),
            ],
        ),
    ]
