# Generated by Django 2.0 on 2017-12-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='recruitment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Recruitment'),
        ),
    ]
